- codec_name: default
  match_src: []
  match_dest: []
  except_src: []
  except_dest: []
  packet_codec: ros
  miniframe_header: [0xac]
  dataframe_header: []
  remove_headers: true
  message_codecs:
    - id: 1
      message_codec: default
      subscribe_topic: "/status"
      publish_topic: "/from_acomms/status"
      ros_type: "ros_remus/Status"
      default_dest: 121
      queue_order: lifo
      queue_maxsize: 1
      is_active: true
      allow_fragmentation: false
      priority: 30
      fields:
        latitude:
          codec: float
          min_value: -90
          max_value: 90
          precision: 5
        longitude:
          codec: float
          min_value: -180
          max_value: 180
          precision: 5
        depth:
          codec: float
          min_value: 0
          max_value: 6000
          precision: 1
        depth_goal:
          codec: integer
          min_value: 0
          max_value: 6000
        altitude:
          codec: float
          min_value: 0
          max_value: 1000
          precision: 1
        pitch:
          codec: float
          min_value: -90
          max_value: 90
          precision: 1
        roll:
          codec: float
          min_value: -90
          max_value: 90
          precision: 1
        thruster_rpm:
          codec: integer
          min_value: -1500
          max_value: 1500
        thruster_rpm_goal:
          codec: integer
          min_value: -1500
          max_value: 1500
        velocity:
          codec: float
          min_value: -5
          max_value: 5
          precision: 2
        heading:
          codec: integer
          min_value: 0
          max_value: 360
        leg_num:
          codec: integer
          min_value: 0
          max_value: 510
        override_enabled:
          codec: bool
        override_active:
          codec: bool
        override_allowed:
          codec: bool
        major_fault:
          codec: bool
    - id: 2
      message_codec: default
      subscribe_topic: "/atr_contact"
      publish_topic: "/from_acomms/atr_contact"
      ros_type: "ros_remus/ATRContact"
      default_dest: 121
      queue_order: lifo
      queue_maxsize: 1
      allow_fragmentation: false
      priority: 20
      fields:
        contact_ID:
          codec: integer
          min_value: 0
          max_value: 2000000000
        contact_time:
          codec: integer
          min_value: 0
          max_value: 2000000000
        c_tgt_lat:
          codec: float
          min_value: -90
          max_value: 90
          precision: 5
        c_tgt_lon:
          codec: float
          min_value: -180
          max_value: 180
          precision: 5
        c_tgt_depth:
          codec: float
          min_value: 0
          max_value: 6000
          precision: 1
        c_tgt_alt:
          codec: float
          min_value: 0
          max_value: 1000
          precision: 1
        c_tgt_class:
          codec: integer
          min_value: -128
          max_value: 127
        c_tgt_class_rate:
          codec: float
          min_value: 0
          max_value: 100
          precision: 0
    - id: 3
      message_codec: default
      subscribe_topic: "/atr_snippet"
      publish_topic: "/from_acomms/atr_snippet"
      ros_type: "baltops/AtrSnippet"
      default_dest: 121
      queue_order: fifo
      queue_maxsize: 5
      allow_fragmentation: true
      priority: 20
      fields:
        contact_ID:
          codec: integer
          min_value: 0
          max_value: 2000000000
        contact_time:
          codec: integer
          min_value: 0
          max_value: 2000000000
        c_tgt_lat:
          codec: float
          min_value: -90
          max_value: 90
          precision: 5
        c_tgt_lon:
          codec: float
          min_value: -180
          max_value: 180
          precision: 5
        c_tgt_depth:
          codec: float
          min_value: 0
          max_value: 6000
          precision: 1
        c_tgt_alt:
          codec: float
          min_value: 0
          max_value: 1000
          precision: 1
        c_tgt_class:
          codec: integer
          min_value: -128
          max_value: 127
        c_tgt_class_rate:
          codec: float
          min_value: 0
          max_value: 100
          precision: 0
        image_file_bytes:
          codec: bytes
          max_length: 65535
