Header header

int8 MEASUREMENT_TYPE_UNKNOWN = 0
int8 MEASUREMENT_TYPE_OWTT = 1
int8 MEASUREMENT_TYPE_TWTT = 2
int8 measurement_type

int8 SPEED_OF_SOUND_SOURCE_INVALID = -1
int8 SPEED_OF_SOUND_SOURCE_UNKNOWN = 0
int8 SPEED_OF_SOUND_SOURCE_STATIC = 1
int8 SPEED_OF_SOUND_SOURCE_TOPIC = 2
int8 SPEED_OF_SOUND_SOURCE_INVERTED_FROM_DISTANCE = 3
int8 speed_of_sound_source

int16 src
int16 dest

float32 owtt
float32 tat

float32 range_m
float32 speed_of_sound_ms

CST cst
