# SNNST statistics for Nav commands
Header header
int8 version
int16 ftx
int16 ttx
time query_time
int16 nav_agn
int16 tat

# "A" Transponder response metrics
float32 a1_owtt
int16 a1_pk
int16 a1_pow
int16 a1_ratio
int16 a1_frx

# "B" Transponder response metrics
float32 b2_owtt
int16 b2_pk
int16 b2_pow
int16 b2_ratio
int16 b2_frx

# "C" Transponder response metrics
float32 c3_owtt
int16 c3_pk
int16 c3_pow
int16 c3_ratio
int16 c3_frx

# "D" Transponder response metrics
float32 d4_owtt
int16 d4_pk
int16 d4_pow
int16 d4_ratio
int16 d4_frx
